# Generated by Django 2.2 on 2021-05-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpTable',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('empID', models.AutoField(primary_key=True, serialize=False)),
                ('empName', models.CharField(max_length=150)),
                ('empEmail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('empAddress', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddIndex(
            model_name='emptable',
            index=models.Index(fields=['empID', 'empEmail'], name='users_empta_empID_563a2d_idx'),
        ),
    ]
